### ISSUE TITLE
Will you release codes for real-robot experiments?

### ISSUE THREAD

**Issue by TongZhangTHU** [peract/peract#18]
Hi,  thank you again for your wonderful work. 

Is there any plan to release codes for real-robot experiments?

**Comment by MohitShridhar** [comment]
@TongZhangTHU, the PerAct part of the code for real-robot experiments is exactly the same as in this repo. The [real-world datasets](https://github.com/peract/peract/issues/2) looks identical to sim datasets. The input (voxel grids + language) and outputs (discretized actions) are also identical. 

The actual ROS code that interfaces everything together in the real-world is a mess and hard to open-source because it's just a bunch of hacked together code specific to my setup. But if it helps, here are all the tools I used:

- Data collection: Checkout this [video](https://youtu.be/TB0g52N-3_Y?t=94). The interface is just a HTC vive controller that provides 6-DoF poses, then I use a [motion planner](https://ros-planning.github.io/moveit_tutorials/) to reach them.
- HTC Vive Controller: See [setup guide](https://www.roadtovr.com/how-to-use-the-htc-vive-tracker-without-a-vive-headset/) and [ROS interface](https://github.com/uts-magic-lab/htc_vive_teleop_stuff). Everytime I click a button, it's basically recorded as a keyframe pose. Then I record all the camera and sensor data while the motion-planner tries to reach the target pose. Agent execution is basically the same, except the target poses come from the trained PerAct agent. The agent is used in an observe-act loop until I say stop. 
- Kinect: I used [iai_kinect2](https://github.com/code-iai/iai_kinect2)
- Hand-eye calibration for camera to robot base transformation: [easy_handeye](https://github.com/IFL-CAMP/easy_handeye). I attached an ARUCO marker on the gripper, and recorded automated poses with easy_handeye. 
- Visualization: All the visualization code is in this [Colab Notebook
(https://colab.research.google.com/drive/1wpaosDS94S0rmtGmdnP0J1TjS7mEM14V?usp=sharing). See the bottommost cell for the gripper prediction visualization.
- RViz marker for visualizing (green) gripper: http://wiki.ros.org/rviz/DisplayTypes/Marker

I have also attached my scripts for collecting datasets and executing PerAct outputs. They are a bit hard to read. Hope this helps! 
[franka_htc_teleop (1).zip](https://github.com/peract/peract/files/11035550/franka_htc_teleop.1.zip)

**Comment by TongZhangTHU** [comment]
Thank you so much for your kind help!

**Comment by TongZhangTHU** [comment]
Thank you for sharing your scripts for collecting datasets. Another question is how to install 'dvnets_franka' and 'dvnets_franka_msgs' package which is used in your scripts. I can't find a way to install them.

**Comment by MohitShridhar** [comment]
@TongZhangTHU, sorry it looks like I zipped the wrong files.

Here is the updated zip:
[franka_htc_teleop.zip](https://github.com/peract/peract/files/11362196/franka_htc_teleop.zip)

`peract_demo_interface.py` for collecting data, and `peract_agent_interface.py` is for executing trained models.

**Comment by TongZhangTHU** [comment]
@MohitShridhar Thank you for your help!

**Comment by MohitShridhar** [comment]
@TongZhangTHU, this could mean either:
1. The hand-eye calibration was completed and saved, but that transformation is not being used in the TF tree. You might need a [static transform publisher](http://wiki.ros.org/tf#static_transform_publisher) that publishes the TF between camera and robot base.
2. Something went wrong with the hand-eye calibration. You can look at the translation and rotation values and see if that transformation makes sense to you.

**Comment by TongZhangTHU** [comment]
@MohitShridhar Did you publish the TF by easy_handeye, such as  `roslaunch easy_handeye publish.launch eye_on_hand:=false namespace_prefix:=panda_eob_calib`? We simply use this command for TF publish. Is this right?

**Comment by devvaibhav455** [comment]
@MohitShridhar Thanks for providing the code. I am trying to understand it and have a few queries. Can you please help to answer them?

1) How did you generate the visualization marker? I have worked with very simple markers in which I defined a set of points that get displayed in rviz. How did you show the green thing for just the end effector ( by manually defining points or something else takes care of that)?
2) Who publishes the topic '/target_gripper' as defined in the `peract_demo.yaml` file?

**Comment by MohitShridhar** [comment]
@TongZhangTHU. That should also work. It had a custom script like this:

```python
#!/usr/bin/env python
import rospy
import yaml

# to get commandline arguments
import sys

# because of transformations
import tf

import tf2_ros
import geometry_msgs.msg

if __name__ == '__main__':
    if len(sys.argv) < 1:
        rospy.logerr('Missing yaml file in args')
        sys.exit(0)
    else:
        yaml_file = sys.argv[1]
        with open(yaml_file, 'r') as file:
            calib = yaml.safe_load(file)

        print(calib)

        rospy.init_node('my_static_tf2_broadcaster')
        broadcaster = tf2_ros.StaticTransformBroadcaster()

        while not rospy.is_shutdown():
            static_transformStamped = geometry_msgs.msg.TransformStamped()

            static_transformStamped.header.stamp = rospy.Time.now()
            static_transformStamped.header.frame_id = "panda_link0"
            static_transformStamped.child_frame_id = "kinect_front_link"

            static_transformStamped.transform.translation.x = calib['transformation']['x']
            static_transformStamped.transform.translation.y = calib['transformation']['y']
            static_transformStamped.transform.translation.z = calib['transformation']['z']

            static_transformStamped.transform.rotation.x = calib['transformation']['qx']
            static_transformStamped.transform.rotation.y = calib['transformation']['qy']
            static_transformStamped.transform.rotation.z = calib['transformation']['qz']
            static_transformStamped.transform.rotation.w = calib['transformation']['qw']

            broadcaster.sendTransform(static_transformStamped)
            rospy.sleep(0.01)
```

**Comment by MohitShridhar** [comment]
@devvaibhav455, checkout `vive_franka_teleop.py` inside [franka_htc_teleop.zip](https://github.com/peract/peract/files/11362196/franka_htc_teleop.zip). It simply loads the gripper mesh and publishes it as an Rviz marker.

**Comment by Sid0225** [comment]
@MohitShridhar  I am trying to replicate the setup(with no HMD) but looks like I am facing issues with steamVR version, can you please tell your steamVR (beta or non beta with their versions) ?

**Comment by Sid0225** [comment]
> @Sid0225, I don't think the SteamVR version matters. But you just have to set `requireHmd: False`. See this: [#10 (comment)](https://github.com/peract/peract/issues/10#issuecomment-1378179384)

@MohitShridhar  I have already tried that and the other settings but they didn't work I suspect they changed something in the newer versions. Therefore, wanted to revert back to the version you tried it on.

**Comment by MohitShridhar** [comment]
<img width="485" alt="image" src="https://github.com/peract/peract/assets/6535354/5e191079-16b9-43c6-9a53-59d2f7ecf103">

Thanks to @jiafei1224!

**Comment by scut-shpan** [comment]
> [@TongZhangTHU](https://github.com/TongZhangTHU), the PerAct part of the code for real-robot experiments is exactly the same as in this repo. The [real-world datasets](https://github.com/peract/peract/issues/2) looks identical to sim datasets. The input (voxel grids + language) and outputs (discretized actions) are also identical.
> 
> The actual ROS code that interfaces everything together in the real-world is a mess and hard to open-source because it's just a bunch of hacked together code specific to my setup. But if it helps, here are all the tools I used:
> 
>     * Data collection: Checkout this [video](https://youtu.be/TB0g52N-3_Y?t=94). The interface is just a HTC vive controller that provides 6-DoF poses, then I use a [motion planner](https://ros-planning.github.io/moveit_tutorials/) to reach them.
> 
>     * HTC Vive Controller: See [setup guide](https://www.roadtovr.com/how-to-use-the-htc-vive-tracker-without-a-vive-headset/) and [ROS interface](https://github.com/uts-magic-lab/htc_vive_teleop_stuff). Everytime I click a button, it's basically recorded as a keyframe pose. Then I record all the camera and sensor data while the motion-planner tries to reach the target pose. Agent execution is basically the same, except the target poses come from the trained PerAct agent. The agent is used in an observe-act loop until I say stop.
> 
>     * Kinect: I used [iai_kinect2](https://github.com/code-iai/iai_kinect2)
> 
>     * Hand-eye calibration for camera to robot base transformation: [easy_handeye](https://github.com/IFL-CAMP/easy_handeye). I attached an ARUCO marker on the gripper, and recorded automated poses with easy_handeye.
> 
>     * Visualization: All the visualization code is in this [Colab Notebook
>       (https://colab.research.google.com/drive/1wpaosDS94S0rmtGmdnP0J1TjS7mEM14V?usp=sharing). See the bottommost cell for the gripper prediction visualization.
> 
>     * RViz marker for visualizing (green) gripper: http://wiki.ros.org/rviz/DisplayTypes/Marker
> 
> 
> I have also attached my scripts for collecting datasets and executing PerAct outputs. They are a bit hard to read. Hope this helps! [franka_htc_teleop (1).zip](https://github.com/peract/peract/files/11035550/franka_htc_teleop.1.zip)

there is no files in this website, and could you please share those files again?

**Comment by MughniIrfan** [comment]
Thanks a lot for including the zip file, Could you please share the config file also. Would be very helpful
