### ISSUE TITLE
Questions about the details

### ISSUE THREAD

**Issue by JisuHann** [peract/peract#33]
Hi, thanks for your splendid work!
I have some questions regarding some implementation details.

1. I would like to implement peract at other datasets, but it requires to extract the key-frame actions. I wonder is there any algorithm to extract the key-frame action.
2. I am curious about the choice of the multi-tasks. Is there any reason you chose 18 tasks among the 100 tasks from RLBench?

Thank you!

**Comment by MohitShridhar** [comment]
@JisuHann 
1. This is specific to your dataset setup. In simulation, you can probably use some heuristics (like the one we use for RLBench). For real-world setups, you can simply press a button to record the keypoint.
2. I chose tasks that had greater than 1 variation, otherwise there would be no use for the language commands. You can probably train PerAct on more tasks.

**Comment by JisuHann** [comment]
Thank you!
